version: '3'

services:
  postgres:
      image: postgres:16.2-alpine
      ports:
        - "5432:5432"
      restart: always
      environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: "benchmark"
      volumes:
        - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql